/**
 * ZIP Builder
 *
 * Assembles the three generated Terraform files into a single in-memory ZIP
 * archive using JSZip and returns a Node.js Buffer ready to be streamed to
 * the HTTP response.
 *
 * Archive structure:
 *   terraform/
 *     providers.tf
 *     variables.tf
 *     main.tf
 */

import JSZip from 'jszip';
import { MappedResource } from '../../types/index';
import { buildMainTf, buildVariablesTf, buildProvidersTf, buildResourceBlock } from './hclTemplates';

export type TerraformLayout = 'flat' | 'modular';

export type ZipContents = Record<string, string>;

/**
 * Generates Terraform file contents from the provided resources.
 */
export function buildTerraformContents(resources: MappedResource[], layout: TerraformLayout = 'flat'): ZipContents {
  if (layout === 'modular') {
    return buildModularContents(resources);
  }

  return {
    'providers.tf': buildProvidersTf(),
    'variables.tf': buildVariablesTf(resources),
    'main.tf': buildMainTf(resources),
  };
}

function buildModularContents(resources: MappedResource[]): ZipContents {
  const files: ZipContents = {
    'providers.tf': buildProvidersTf(),
    'variables.tf': buildVariablesTf(resources),
  };

  const idToModuleAddress = new Map<string, string>();
  for (const r of resources) {
    idToModuleAddress.set(r.node.id, `module.${r.resourceName}`);
  }

  const rootMain: string[] = [
    '# Modular root - generated by D2C Draw.io -> Terraform Converter',
    '# Each resource is placed under modules/<resource_name>/main.tf',
    '',
  ];

  for (const resource of resources) {
    rootMain.push(`module "${resource.resourceName}" {`);
    rootMain.push(`  source = "./modules/${resource.resourceName}"`);

    const depModules = resource.dependencies
      .map(id => idToModuleAddress.get(id))
      .filter((addr): addr is string => addr !== undefined);

    if (depModules.length > 0) {
      rootMain.push('');
      rootMain.push('  depends_on = [');
      for (const dep of depModules) {
        rootMain.push(`    ${dep},`);
      }
      rootMain.push('  ]');
    }

    rootMain.push('}');
    rootMain.push('');

    files[`modules/${resource.resourceName}/main.tf`] =
      buildResourceBlock(resource).join('\n') + '\n';
  }

  files['main.tf'] = rootMain.join('\n');
  return files;
}

/**
 * Creates a ZIP archive containing the three Terraform files.
 *
 * @param contents - Pre-generated file contents (or call `buildTerraformContents` first)
 * @returns         A Buffer containing the complete ZIP archive.
 */
export async function buildZip(contents: ZipContents): Promise<Buffer> {
  const zip = new JSZip();
  const folder = zip.folder('terraform')!;

  for (const [relativePath, content] of Object.entries(contents)) {
    folder.file(relativePath, content, { date: new Date() });
  }

  const buffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return buffer;
}
