/**
 * ZIP Builder
 *
 * Assembles the three generated Terraform files into a single in-memory ZIP
 * archive using JSZip and returns a Node.js Buffer ready to be streamed to
 * the HTTP response.
 *
 * Archive structure:
 *   terraform/
 *     providers.tf
 *     variables.tf
 *     main.tf
 */

import JSZip from 'jszip';
import { MappedResource } from '../../types/index';
import {
  buildMainTf,
  buildVariablesTf,
  buildProvidersTf,
  buildResourceBlock,
  formatHclValue,
} from './hclTemplates';

export type TerraformLayout = 'flat' | 'modular';

export type ZipContents = Record<string, string>;

/**
 * Generates Terraform file contents from the provided resources.
 */
export function buildTerraformContents(resources: MappedResource[], layout: TerraformLayout = 'flat'): ZipContents {
  if (layout === 'modular') {
    return buildModularContents(resources);
  }

  return {
    'providers.tf': buildProvidersTf(),
    'variables.tf': buildVariablesTf(resources),
    'main.tf': buildMainTf(resources),
  };
}

function buildModularContents(resources: MappedResource[]): ZipContents {
  const files: ZipContents = {
    'providers.tf': buildProvidersTf(),
    'variables.tf': buildVariablesTf(resources),
  };

  const idToModuleAddress = new Map<string, string>();
  const resourceAddressToModuleOutput = new Map<string, string>();
  for (const r of resources) {
    idToModuleAddress.set(r.node.id, `module.${r.resourceName}`);
    resourceAddressToModuleOutput.set(
      `${r.terraformType}.${r.resourceName}.id`,
      `module.${r.resourceName}.id`
    );
  }

  const rootMain: string[] = [
    '# Modular root - generated by D2C Draw.io -> Terraform Converter',
    '# Each resource is placed under modules/<resource_name>/',
    '# with its own main.tf, variables.tf and output.tf',
    '',
  ];

  const rootOutputs: string[] = [
    '# Root outputs from all modules',
    '',
  ];

  for (const resource of resources) {
    rootMain.push(`module "${resource.resourceName}" {`);
    rootMain.push(`  source = "./modules/${resource.resourceName}"`);

    // Pass module input variables from the mapped argument set.
    const sortedArgs = Object.entries(resource.arguments).sort(([a], [b]) => a.localeCompare(b));
    for (const [key, rawVal] of sortedArgs) {
      const rewritten = rewriteCrossModuleReference(rawVal, resourceAddressToModuleOutput);
      rootMain.push(`  ${key} = ${formatHclValue(rewritten)}`);
    }

    const depModules = resource.dependencies
      .map(id => idToModuleAddress.get(id))
      .filter((addr): addr is string => addr !== undefined);

    if (depModules.length > 0) {
      rootMain.push('');
      rootMain.push('  depends_on = [');
      for (const dep of depModules) {
        rootMain.push(`    ${dep},`);
      }
      rootMain.push('  ]');
    }

    rootMain.push('}');
    rootMain.push('');

    // Module files: main.tf, variables.tf, output.tf
    files[`modules/${resource.resourceName}/main.tf`] =
      buildModuleMainTf(resource);
    files[`modules/${resource.resourceName}/variables.tf`] =
      buildModuleVariablesTf(resource);
    files[`modules/${resource.resourceName}/output.tf`] =
      buildModuleOutputTf(resource);

    rootOutputs.push(`output "${resource.resourceName}_id" {`);
    rootOutputs.push(`  value       = module.${resource.resourceName}.id`);
    rootOutputs.push(`  description = "ID of ${resource.terraformType}.${resource.resourceName}"`);
    rootOutputs.push('}');
    rootOutputs.push('');
  }

  files['main.tf'] = rootMain.join('\n');
  files['outputs.tf'] = rootOutputs.join('\n');
  return files;
}

function rewriteCrossModuleReference(
  value: string,
  addressToModuleOutput: Map<string, string>
): string {
  const trimmed = value.trim();
  const rewritten = addressToModuleOutput.get(trimmed);
  return rewritten ?? value;
}

function buildModuleMainTf(resource: MappedResource): string {
  // Module resource arguments come from input vars, so the root module controls
  // wiring and ordering while each module stays reusable.
  const variableArgs: Record<string, string> = {};
  for (const key of Object.keys(resource.arguments)) {
    variableArgs[key] = `var.${key}`;
  }

  const moduleResource: MappedResource = {
    ...resource,
    arguments: variableArgs,
    dependencies: [],
  };

  return buildResourceBlock(moduleResource).join('\n') + '\n';
}

function buildModuleVariablesTf(resource: MappedResource): string {
  const lines: string[] = [];
  const keys = Object.keys(resource.arguments).sort((a, b) => a.localeCompare(b));

  if (keys.length === 0) {
    return '# This module has no input variables.\n';
  }

  for (const key of keys) {
    lines.push(`variable "${key}" {`);
    lines.push('  type = any');
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

function buildModuleOutputTf(resource: MappedResource): string {
  const lines: string[] = [];
  lines.push('output "id" {');
  lines.push(`  value = ${resource.terraformType}.${resource.resourceName}.id`);
  lines.push('}');
  lines.push('');
  return lines.join('\n');
}

/**
 * Creates a ZIP archive containing the three Terraform files.
 *
 * @param contents - Pre-generated file contents (or call `buildTerraformContents` first)
 * @returns         A Buffer containing the complete ZIP archive.
 */
export async function buildZip(contents: ZipContents): Promise<Buffer> {
  const zip = new JSZip();
  const folder = zip.folder('terraform')!;

  for (const [relativePath, content] of Object.entries(contents)) {
    folder.file(relativePath, content, { date: new Date() });
  }

  const buffer = await zip.generateAsync({
    type: 'nodebuffer',
    compression: 'DEFLATE',
    compressionOptions: { level: 6 },
  });

  return buffer;
}
